name: 'Deploy'

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-tags:
    runs-on: ubuntu-latest
    steps:
      - name: install tree zip
        run: sudo apt update && sudo apt upgrade -y && sudo apt install tree zip -y

      - name: Get tag name
        id: tag
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - uses: actions/checkout@v3

      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.0.2

      - name: build twig cache
        run: ./build_twig_cache.sh

      - name: build plugin deploy
        run: ./gradlew --build-cache clean buildPlugin

      - name: deploy plugin to marketplace
        run: ./gradlew publishPlugin

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag.outputs.VERSION }}
          name: Release ${{ steps.tag.outputs.VERSION }}
          body: cat CHANGELOG.md
          artifacts: "./build/distributions/*.zip"