name: 'Main'

# **What it does**: Renders the content of every page and check all internal links.
# **Why we have it**: To make sure all links connect correctly.
# **Who does it impact**: Docs content.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  # Needed for the 'trilom/file-changes-action' action
  pull-requests: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: set gradle opts
        uses: allenevans/set-env@v2.0.0
        with:
          GRADLE_OPTS: '-Dorg.gradle.daemon=false'
      - name: set gradle user home
        run: export GRADLE_USER_HOME=`pwd`/.gradle
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: create chain credentials
        uses: finnp/create-file-action@1.0.0
        env:
          FILE_NAME: ".ssl-keys/chain.crt"
          FILE_DATA: $CHAIN_CERT
      - name: create chain credentials
        uses: finnp/create-file-action@1.0.0
        env:
          FILE_NAME: ".ssl-keys/private.pem"
          FILE_DATA: $PRIVATE_PEM
      - name: create chain credentials
        uses: finnp/create-file-action@1.0.0
        env:
          FILE_NAME: ".ssl-keys/password.txt"
          FILE_DATA: $PASSWORD_TXT
      - name: Build with Gradle
        run: ./gradlew --build-cache clean buildPlugin
      - name: upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/distributions
  tests:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: install tree
        run: sudo apt update && sudo apt install tree -y
      - name: set gradle opts
        uses: allenevans/set-env@v2.0.0
        with:
          GRADLE_OPTS: '-Dorg.gradle.daemon=false'
      - name: set gradle user home
        run: export GRADLE_USER_HOME=`pwd`/.gradle
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: create chain credentials
        uses: finnp/create-file-action@1.0.0
        env:
          FILE_NAME: ".ssl-keys/chain.crt"
          FILE_DATA: $CHAIN_CERT
      - name: create chain credentials
        uses: finnp/create-file-action@1.0.0
        env:
          FILE_NAME: ".ssl-keys/private.pem"
          FILE_DATA: $PRIVATE_PEM
      - name: create chain credentials
        uses: finnp/create-file-action@1.0.0
        env:
          FILE_NAME: ".ssl-keys/password.txt"
          FILE_DATA: $PASSWORD_TXT
      - name: build twig cache
        run: ./build_twig_cache.sh
      - name: Run tests
        run: ./gradlew test